In [6]:
import numpy as np

m = np.ones((2, 3))  # Shape: (2, 3)
v = np.arange(3)  # Shape: (3,)
print(m)
print(v)
result = m + v 
# print(result)
# print(result.shape)



[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
